// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Signed-out previews for the /learn surfaces (browse-first UX): instead of
// bouncing a curious visitor to the login page, show what's inside and why
// it needs an identity. Mutations still redirect — these render on GET only.

// QuizTeaser previews the quiz for signed-out visitors.
func QuizTeaser() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div data-testid=\"quiz-teaser\" class=\"bg-surface rounded-lg shadow-md p-6\"><h2 class=\"text-xl font-semibold mb-2\">Ten questions about the machine you're standing in</h2><p class=\"mb-3 text-muted-foreground\">The quiz covers this starter's own architecture — routing and middleware, handlers, the RLS-scoped data layer, the templ/HTMX frontend, and the performance budgets. Every answer you submit is written as a real row, scoped to you by Postgres Row Level Security.</p><p class=\"mb-5 text-muted-foreground\">That's why it asks you to sign in: your score, your attempts, and the flashcards you save are per-user data on the same multi-tenant path a production app would use — not a cookie full of JSON.</p><div class=\"flex flex-wrap gap-3\"><a href=\"/auth/page\" class=\"btn btn-primary inline-block\">Sign in to start</a> <a href=\"/auth/page?mode=signup\" class=\"btn btn-secondary inline-block\">Create an account</a></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// FlashcardsTeaser previews the flashcard review for signed-out visitors.
func FlashcardsTeaser() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div data-testid=\"flashcards-teaser\" class=\"bg-surface rounded-lg shadow-md p-6\"><h2 class=\"text-xl font-semibold mb-2\">Your wrong answers, working for you</h2><p class=\"mb-3 text-muted-foreground\">Miss a question on the <a href=\"/learn/quiz\" class=\"text-link underline\">architecture quiz</a> and you can save it as a flashcard — then review, flip, mark what you know, and delete what you don't need.</p><p class=\"mb-5 text-muted-foreground\">Each card is a row that belongs to you, enforced by Row Level Security at the database — which is why this page needs to know who you are.</p><div class=\"flex flex-wrap gap-3\"><a href=\"/auth/page\" class=\"btn btn-primary inline-block\">Sign in to review</a> <a href=\"/auth/page?mode=signup\" class=\"btn btn-secondary inline-block\">Create an account</a></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
