// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/clownware/alpine-go-performance-starter/internal/view"
	"github.com/clownware/alpine-go-performance-starter/internal/view/layouts"
	"github.com/clownware/alpine-go-performance-starter/internal/view/partials"
)

type DashboardPageProps struct {
	view.BaseProps
	HasProjects bool
}

// dashboardSkeletonData returns the Alpine.js x-data expression for the skeleton loader.
func dashboardSkeletonData() string {
	return "{ loading: true }"
}

func DashboardPage(props DashboardPageProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"max-w-3xl mx-auto bg-surface text-text dark:bg-surface-dark dark:text-text-dark rounded shadow p-6 mt-12\"><h1 class=\"text-3xl font-bold\">Dashboard</h1><p>Welcome to your dashboard. This page is ready for your custom SaaS widgets and stats.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !props.HasProjects {
				templ_7745c5c3_Err = partials.EmptyState(partials.EmptyStateProps{}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if props.HasProjects {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div x-data=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(dashboardSkeletonData())
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/view/pages/dashboard.templ`, Line: 29, Col: 37}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" @htmx:beforeSwap.window=\"loading = false\" class=\"mt-10\"><!-- Skeleton Loader --><div x-show=\"loading\" x-transition.opacity.duration.500ms class=\"space-y-2\" aria-hidden=\"true\"><div class=\"animate-pulse flex space-x-4\"><div class=\"rounded bg-muted-dark h-6 w-1/4\"></div><div class=\"rounded bg-muted-dark h-6 w-1/4\"></div><div class=\"rounded bg-muted-dark h-6 w-1/4\"></div></div><div class=\"animate-pulse flex space-x-4\"><div class=\"rounded bg-muted-dark h-6 w-1/4\"></div><div class=\"rounded bg-muted-dark h-6 w-1/4\"></div><div class=\"rounded bg-muted-dark h-6 w-1/4\"></div></div><div class=\"animate-pulse flex space-x-4\"><div class=\"rounded bg-muted-dark h-6 w-1/4\"></div><div class=\"rounded bg-muted-dark h-6 w-1/4\"></div><div class=\"rounded bg-muted-dark h-6 w-1/4\"></div></div></div><!-- Real Table Data (to be swapped in by HTMX) --><div x-show=\"!loading\" x-transition.opacity.duration.500ms id=\"dashboard-table\" hx-get=\"/dashboard/data\" hx-trigger=\"load\" hx-target=\"#dashboard-table\" hx-swap=\"outerHTML\"></div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base(props.BaseProps).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
