// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flashcards.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFlashcard = `-- name: CreateFlashcard :one
INSERT INTO flashcards (
    user_id, question_id, front, back
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, question_id, front, back, is_known, created_at, updated_at
`

type CreateFlashcardParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	QuestionID pgtype.UUID `json:"question_id"`
	Front      string      `json:"front"`
	Back       string      `json:"back"`
}

func (q *Queries) CreateFlashcard(ctx context.Context, arg CreateFlashcardParams) (Flashcard, error) {
	row := q.db.QueryRow(ctx, createFlashcard,
		arg.UserID,
		arg.QuestionID,
		arg.Front,
		arg.Back,
	)
	var i Flashcard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.Front,
		&i.Back,
		&i.IsKnown,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFlashcard = `-- name: DeleteFlashcard :exec
DELETE FROM flashcards
WHERE id = $1 AND user_id = $2
`

type DeleteFlashcardParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteFlashcard(ctx context.Context, arg DeleteFlashcardParams) error {
	_, err := q.db.Exec(ctx, deleteFlashcard, arg.ID, arg.UserID)
	return err
}

const getFlashcard = `-- name: GetFlashcard :one
SELECT id, user_id, question_id, front, back, is_known, created_at, updated_at
FROM flashcards
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFlashcard(ctx context.Context, id uuid.UUID) (Flashcard, error) {
	row := q.db.QueryRow(ctx, getFlashcard, id)
	var i Flashcard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.Front,
		&i.Back,
		&i.IsKnown,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFlashcardsByUser = `-- name: ListFlashcardsByUser :many
SELECT id, user_id, question_id, front, back, is_known, created_at, updated_at
FROM flashcards
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFlashcardsByUser(ctx context.Context, userID uuid.UUID) ([]Flashcard, error) {
	rows, err := q.db.Query(ctx, listFlashcardsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Flashcard{}
	for rows.Next() {
		var i Flashcard
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.QuestionID,
			&i.Front,
			&i.Back,
			&i.IsKnown,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFlashcardKnown = `-- name: SetFlashcardKnown :one
UPDATE flashcards
SET is_known = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, question_id, front, back, is_known, created_at, updated_at
`

type SetFlashcardKnownParams struct {
	ID      uuid.UUID `json:"id"`
	IsKnown bool      `json:"is_known"`
}

func (q *Queries) SetFlashcardKnown(ctx context.Context, arg SetFlashcardKnownParams) (Flashcard, error) {
	row := q.db.QueryRow(ctx, setFlashcardKnown, arg.ID, arg.IsKnown)
	var i Flashcard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.Front,
		&i.Back,
		&i.IsKnown,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
