// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Organization struct {
	ID                uuid.UUID   `json:"id"`
	Name              string      `json:"name"`
	Slug              string      `json:"slug"`
	PlanType          pgtype.Text `json:"plan_type"`
	BillingCustomerID pgtype.Text `json:"billing_customer_id"`
	IsActive          pgtype.Bool `json:"is_active"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
}

type OrganizationMember struct {
	ID                    uuid.UUID   `json:"id"`
	OrganizationID        uuid.UUID   `json:"organization_id"`
	UserID                uuid.UUID   `json:"user_id"`
	Role                  string      `json:"role"`
	IsPrimaryOrganization pgtype.Bool `json:"is_primary_organization"`
	CreatedAt             time.Time   `json:"created_at"`
	UpdatedAt             time.Time   `json:"updated_at"`
}

type User struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	Name        pgtype.Text        `json:"name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	AuthID      pgtype.Text        `json:"auth_id"`
	IsActive    pgtype.Bool        `json:"is_active"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}
