// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Flashcard struct {
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
	QuestionID pgtype.UUID `json:"question_id"`
	Front      string      `json:"front"`
	Back       string      `json:"back"`
	IsKnown    bool        `json:"is_known"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

type Organization struct {
	ID                uuid.UUID   `json:"id"`
	Name              string      `json:"name"`
	Slug              string      `json:"slug"`
	PlanType          pgtype.Text `json:"plan_type"`
	BillingCustomerID pgtype.Text `json:"billing_customer_id"`
	IsActive          pgtype.Bool `json:"is_active"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
}

type OrganizationMember struct {
	ID                    uuid.UUID   `json:"id"`
	OrganizationID        uuid.UUID   `json:"organization_id"`
	UserID                uuid.UUID   `json:"user_id"`
	Role                  string      `json:"role"`
	IsPrimaryOrganization pgtype.Bool `json:"is_primary_organization"`
	CreatedAt             time.Time   `json:"created_at"`
	UpdatedAt             time.Time   `json:"updated_at"`
}

type QuizAttempt struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	QuestionID    uuid.UUID `json:"question_id"`
	SelectedIndex int32     `json:"selected_index"`
	IsCorrect     bool      `json:"is_correct"`
	CreatedAt     time.Time `json:"created_at"`
}

type QuizQuestion struct {
	ID           uuid.UUID `json:"id"`
	Slug         string    `json:"slug"`
	Topic        string    `json:"topic"`
	Prompt       string    `json:"prompt"`
	Choices      []byte    `json:"choices"`
	CorrectIndex int32     `json:"correct_index"`
	Explanation  string    `json:"explanation"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID               uuid.UUID          `json:"id"`
	Email            string             `json:"email"`
	Name             pgtype.Text        `json:"name"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	AuthID           pgtype.Text        `json:"auth_id"`
	IsActive         pgtype.Bool        `json:"is_active"`
	LastLoginAt      pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	FirstRunComplete bool               `json:"first_run_complete"`
}
