// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_members.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOrganizationMembers = `-- name: CountOrganizationMembers :one

SELECT COUNT(*) FROM organization_members
WHERE organization_id = $1
`

// The organization_id from step 1
func (q *Queries) CountOrganizationMembers(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationMembers, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganizationMember = `-- name: CreateOrganizationMember :one
INSERT INTO organization_members (
    organization_id,
    user_id,
    role,
    is_primary_organization
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, organization_id, user_id, role, is_primary_organization, created_at, updated_at
`

type CreateOrganizationMemberParams struct {
	OrganizationID        uuid.UUID   `json:"organization_id"`
	UserID                uuid.UUID   `json:"user_id"`
	Role                  string      `json:"role"`
	IsPrimaryOrganization pgtype.Bool `json:"is_primary_organization"`
}

func (q *Queries) CreateOrganizationMember(ctx context.Context, arg CreateOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, createOrganizationMember,
		arg.OrganizationID,
		arg.UserID,
		arg.Role,
		arg.IsPrimaryOrganization,
	)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.IsPrimaryOrganization,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrganizationMember = `-- name: DeleteOrganizationMember :exec
DELETE FROM organization_members
WHERE organization_id = $1 AND user_id = $2
`

type DeleteOrganizationMemberParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteOrganizationMember(ctx context.Context, arg DeleteOrganizationMemberParams) error {
	_, err := q.db.Exec(ctx, deleteOrganizationMember, arg.OrganizationID, arg.UserID)
	return err
}

const getOrganizationMember = `-- name: GetOrganizationMember :one
SELECT id, organization_id, user_id, role, is_primary_organization, created_at, updated_at FROM organization_members
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrganizationMember(ctx context.Context, id uuid.UUID) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrganizationMember, id)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.IsPrimaryOrganization,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationMemberByUserAndOrg = `-- name: GetOrganizationMemberByUserAndOrg :one
SELECT id, organization_id, user_id, role, is_primary_organization, created_at, updated_at FROM organization_members
WHERE user_id = $1 AND organization_id = $2 LIMIT 1
`

type GetOrganizationMemberByUserAndOrgParams struct {
	UserID         uuid.UUID `json:"user_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetOrganizationMemberByUserAndOrg(ctx context.Context, arg GetOrganizationMemberByUserAndOrgParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrganizationMemberByUserAndOrg, arg.UserID, arg.OrganizationID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.IsPrimaryOrganization,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPrimaryOrganization = `-- name: GetUserPrimaryOrganization :one
SELECT o.id, o.name, o.slug, o.plan_type, o.billing_customer_id, o.is_active, o.created_at, o.updated_at FROM organizations o
JOIN organization_members om ON o.id = om.organization_id
WHERE om.user_id = $1 AND om.is_primary_organization = true AND o.is_active = true
LIMIT 1
`

func (q *Queries) GetUserPrimaryOrganization(ctx context.Context, userID uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getUserPrimaryOrganization, userID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PlanType,
		&i.BillingCustomerID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT id, organization_id, user_id, role, is_primary_organization, created_at, updated_at FROM organization_members
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrganizationMembersParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

func (q *Queries) ListOrganizationMembers(ctx context.Context, arg ListOrganizationMembersParams) ([]OrganizationMember, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembers, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationMember{}
	for rows.Next() {
		var i OrganizationMember
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.IsPrimaryOrganization,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationMembershipsForUser = `-- name: ListOrganizationMembershipsForUser :many
SELECT om.id, om.organization_id, om.user_id, om.role, om.is_primary_organization, om.created_at, om.updated_at, o.name as organization_name
FROM organization_members om
JOIN organizations o ON om.organization_id = o.id
WHERE om.user_id = $1
ORDER BY o.name
`

type ListOrganizationMembershipsForUserRow struct {
	ID                    uuid.UUID   `json:"id"`
	OrganizationID        uuid.UUID   `json:"organization_id"`
	UserID                uuid.UUID   `json:"user_id"`
	Role                  string      `json:"role"`
	IsPrimaryOrganization pgtype.Bool `json:"is_primary_organization"`
	CreatedAt             time.Time   `json:"created_at"`
	UpdatedAt             time.Time   `json:"updated_at"`
	OrganizationName      string      `json:"organization_name"`
}

func (q *Queries) ListOrganizationMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]ListOrganizationMembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationMembershipsForUserRow{}
	for rows.Next() {
		var i ListOrganizationMembershipsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.IsPrimaryOrganization,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrganizations = `-- name: ListUserOrganizations :many
SELECT o.id, o.name, o.slug, o.plan_type, o.billing_customer_id, o.is_active, o.created_at, o.updated_at FROM organizations o
JOIN organization_members om ON o.id = om.organization_id
WHERE om.user_id = $1 AND o.is_active = true
ORDER BY o.name
LIMIT $2 OFFSET $3
`

type ListUserOrganizationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListUserOrganizations(ctx context.Context, arg ListUserOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listUserOrganizations, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.PlanType,
			&i.BillingCustomerID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPrimaryOrganizationStep1 = `-- name: SetPrimaryOrganizationStep1 :exec
UPDATE organization_members
SET is_primary_organization = true,
    updated_at = NOW()
WHERE organization_id = $1 AND user_id = $2
`

type SetPrimaryOrganizationStep1Params struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

// Step 1: Set the target membership as primary
func (q *Queries) SetPrimaryOrganizationStep1(ctx context.Context, arg SetPrimaryOrganizationStep1Params) error {
	_, err := q.db.Exec(ctx, setPrimaryOrganizationStep1, arg.OrganizationID, arg.UserID)
	return err
}

const setPrimaryOrganizationStep2 = `-- name: SetPrimaryOrganizationStep2 :exec
UPDATE organization_members
SET is_primary_organization = false,
    updated_at = NOW()
WHERE user_id = $1 -- The user_id from step 1
  AND organization_id != $2
`

type SetPrimaryOrganizationStep2Params struct {
	UserID         uuid.UUID `json:"user_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

// Step 2: Set all other memberships for the user as non-primary
func (q *Queries) SetPrimaryOrganizationStep2(ctx context.Context, arg SetPrimaryOrganizationStep2Params) error {
	_, err := q.db.Exec(ctx, setPrimaryOrganizationStep2, arg.UserID, arg.OrganizationID)
	return err
}

const updateOrganizationMember = `-- name: UpdateOrganizationMember :one
UPDATE organization_members
SET 
    role = COALESCE($3, role),
    is_primary_organization = COALESCE($4, is_primary_organization),
    updated_at = NOW()
WHERE organization_id = $1 AND user_id = $2
RETURNING id, organization_id, user_id, role, is_primary_organization, created_at, updated_at
`

type UpdateOrganizationMemberParams struct {
	OrganizationID        uuid.UUID   `json:"organization_id"`
	UserID                uuid.UUID   `json:"user_id"`
	Role                  string      `json:"role"`
	IsPrimaryOrganization pgtype.Bool `json:"is_primary_organization"`
}

func (q *Queries) UpdateOrganizationMember(ctx context.Context, arg UpdateOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, updateOrganizationMember,
		arg.OrganizationID,
		arg.UserID,
		arg.Role,
		arg.IsPrimaryOrganization,
	)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.IsPrimaryOrganization,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
