// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    name,
    avatar_url,
    auth_id,
    first_run_complete,
    is_anonymous
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, email, name, avatar_url, auth_id, is_active, last_login_at, created_at, updated_at, first_run_complete, is_anonymous
`

type CreateUserParams struct {
	Email            string      `json:"email"`
	Name             pgtype.Text `json:"name"`
	AvatarUrl        pgtype.Text `json:"avatar_url"`
	AuthID           pgtype.Text `json:"auth_id"`
	FirstRunComplete bool        `json:"first_run_complete"`
	IsAnonymous      bool        `json:"is_anonymous"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
		arg.AuthID,
		arg.FirstRunComplete,
		arg.IsAnonymous,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.AuthID,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstRunComplete,
		&i.IsAnonymous,
	)
	return i, err
}

const deleteExpiredAnonymousUsers = `-- name: DeleteExpiredAnonymousUsers :many
DELETE FROM users
WHERE is_anonymous AND created_at < $1
RETURNING id, auth_id
`

type DeleteExpiredAnonymousUsersRow struct {
	ID     uuid.UUID   `json:"id"`
	AuthID pgtype.Text `json:"auth_id"`
}

// Reaps anonymous guest accounts older than the TTL (ADR-024). Upgraded
// accounts have is_anonymous=false and are exempt. Flashcards and quiz
// attempts cascade via their user_id foreign keys.
func (q *Queries) DeleteExpiredAnonymousUsers(ctx context.Context, createdAt time.Time) ([]DeleteExpiredAnonymousUsersRow, error) {
	rows, err := q.db.Query(ctx, deleteExpiredAnonymousUsers, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeleteExpiredAnonymousUsersRow{}
	for rows.Next() {
		var i DeleteExpiredAnonymousUsersRow
		if err := rows.Scan(&i.ID, &i.AuthID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET is_active = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, avatar_url, auth_id, is_active, last_login_at, created_at, updated_at, first_run_complete, is_anonymous
FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.AuthID,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstRunComplete,
		&i.IsAnonymous,
	)
	return i, err
}

const getUserByAuthID = `-- name: GetUserByAuthID :one
SELECT id, email, name, avatar_url, auth_id, is_active, last_login_at, created_at, updated_at, first_run_complete, is_anonymous
FROM users
WHERE auth_id = $1 LIMIT 1
`

func (q *Queries) GetUserByAuthID(ctx context.Context, authID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAuthID, authID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.AuthID,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstRunComplete,
		&i.IsAnonymous,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, avatar_url, auth_id, is_active, last_login_at, created_at, updated_at, first_run_complete, is_anonymous
FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.AuthID,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstRunComplete,
		&i.IsAnonymous,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, avatar_url, auth_id, is_active, last_login_at, created_at, updated_at, first_run_complete, is_anonymous
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
			&i.AuthID,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstRunComplete,
			&i.IsAnonymous,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permanentDeleteUser = `-- name: PermanentDeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) PermanentDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, permanentDeleteUser, id)
	return err
}

const setUserFirstRunComplete = `-- name: SetUserFirstRunComplete :exec
UPDATE users
SET first_run_complete = $2, updated_at = NOW()
WHERE id = $1
`

type SetUserFirstRunCompleteParams struct {
	ID               uuid.UUID `json:"id"`
	FirstRunComplete bool      `json:"first_run_complete"`
}

func (q *Queries) SetUserFirstRunComplete(ctx context.Context, arg SetUserFirstRunCompleteParams) error {
	_, err := q.db.Exec(ctx, setUserFirstRunComplete, arg.ID, arg.FirstRunComplete)
	return err
}

const setUserIsAnonymous = `-- name: SetUserIsAnonymous :exec
UPDATE users
SET is_anonymous = $2, updated_at = NOW()
WHERE id = $1
`

type SetUserIsAnonymousParams struct {
	ID          uuid.UUID `json:"id"`
	IsAnonymous bool      `json:"is_anonymous"`
}

// Guest → registered upgrade (#68): flipping to false exempts the row from
// the anonymous-user reaper.
func (q *Queries) SetUserIsAnonymous(ctx context.Context, arg SetUserIsAnonymousParams) error {
	_, err := q.db.Exec(ctx, setUserIsAnonymous, arg.ID, arg.IsAnonymous)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    email = COALESCE($2, email),
    name = COALESCE($3, name),
    avatar_url = COALESCE($4, avatar_url),
    auth_id = COALESCE($5, auth_id),
    is_active = COALESCE($6, is_active),
    last_login_at = COALESCE($7, last_login_at),
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, avatar_url, auth_id, is_active, last_login_at, created_at, updated_at, first_run_complete, is_anonymous
`

type UpdateUserParams struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	Name        pgtype.Text        `json:"name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	AuthID      pgtype.Text        `json:"auth_id"`
	IsActive    pgtype.Bool        `json:"is_active"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
		arg.AuthID,
		arg.IsActive,
		arg.LastLoginAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.AuthID,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstRunComplete,
		&i.IsAnonymous,
	)
	return i, err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users
SET name = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, avatar_url, auth_id, is_active, last_login_at, created_at, updated_at, first_run_complete, is_anonymous
`

type UpdateUserNameParams struct {
	ID   uuid.UUID   `json:"id"`
	Name pgtype.Text `json:"name"`
}

// Profile self-service rename (#70). Deliberately narrow — the generic
// UpdateUser's COALESCE params make a name-only change thread every other
// column through untouched.
func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.AuthID,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstRunComplete,
		&i.IsAnonymous,
	)
	return i, err
}
