// Command agentsmd generates AGENTS.md (the cross-tool agent spine) from the
// layered constitution sources, or checks that the committed AGENTS.md is in sync.
//
//	go run ./scripts/agentsmd build   # regenerate AGENTS.md
//	go run ./scripts/agentsmd check   # exit non-zero if AGENTS.md is stale
//
// See ADR-022. AGENTS.md is generated — never hand-edit it.
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// sources are concatenated in this order; each file's headings are demoted one
// level so the combined document has a single H1.
var sources = []string{
	"CLAUDE.md",
	".claude/engineering.md",
	".claude/workflow.md",
	".claude/stack.md",
}

const (
	outputPath = "AGENTS.md"
	banner     = "<!-- GENERATED FILE — DO NOT EDIT DIRECTLY. Regenerate with: task agents:build (ADR-022). -->"
	title      = "# Agent Context — Go Performance Starter"
	preamble   = "> Generated from " + "`CLAUDE.md` + `.claude/engineering.md` + `.claude/workflow.md` + `.claude/stack.md`.\n" +
		"> Edit those source layers, then run `task agents:build`. Do not edit this file directly."
)

func main() {
	mode := "build"
	if len(os.Args) > 1 {
		mode = os.Args[1]
	}

	root, err := repoRoot()
	if err != nil {
		fail(err)
	}

	generated, err := generate(root)
	if err != nil {
		fail(err)
	}

	out := filepath.Join(root, outputPath)
	switch mode {
	case "build":
		if err := os.WriteFile(out, generated, 0o644); err != nil {
			fail(err)
		}
		fmt.Printf("✅ Wrote %s (%d bytes) from %d source layers\n", outputPath, len(generated), len(sources))
	case "check":
		current, err := os.ReadFile(out)
		if err != nil {
			fail(fmt.Errorf("reading %s: %w (run `task agents:build`)", outputPath, err))
		}
		if !bytes.Equal(bytes.TrimRight(current, "\n"), bytes.TrimRight(generated, "\n")) {
			fmt.Fprintf(os.Stderr, "❌ %s is out of sync with its sources. Run `task agents:build` and commit the result.\n", outputPath)
			os.Exit(1)
		}
		fmt.Printf("✅ %s is in sync with its sources\n", outputPath)
	default:
		fail(fmt.Errorf("unknown mode %q (want build|check)", mode))
	}
}

func generate(root string) ([]byte, error) {
	var b strings.Builder
	b.WriteString(banner + "\n\n")
	b.WriteString(title + "\n\n")
	b.WriteString(preamble + "\n")

	for _, rel := range sources {
		raw, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			return nil, fmt.Errorf("reading source %s: %w", rel, err)
		}
		b.WriteString("\n---\n\n")
		fmt.Fprintf(&b, "<!-- source: %s -->\n\n", rel)
		b.WriteString(demoteHeadings(string(raw)))
	}

	out := strings.TrimRight(b.String(), "\n") + "\n"
	return []byte(out), nil
}

// demoteHeadings adds one '#' to every ATX heading, capping at H6, while leaving
// content inside fenced code blocks untouched (so shell '#' comments survive).
func demoteHeadings(s string) string {
	lines := strings.Split(s, "\n")
	inFence := false
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "```") || strings.HasPrefix(trimmed, "~~~") {
			inFence = !inFence
			continue
		}
		if inFence {
			continue
		}
		if strings.HasPrefix(line, "#") {
			level := len(line) - len(strings.TrimLeft(line, "#"))
			if level >= 1 && level <= 5 {
				lines[i] = "#" + line
			}
		}
	}
	return strings.Join(lines, "\n")
}

// repoRoot walks up from the working directory until it finds go.mod.
func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found from working directory")
		}
		dir = parent
	}
}

func fail(err error) {
	fmt.Fprintf(os.Stderr, "❌ %v\n", err)
	os.Exit(1)
}
