package main

import (
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// runMainEnv, when set, makes TestMain hand the test binary straight to main()
// so the build/check verdicts (which end in os.Exit) can be asserted from a
// child process without refactoring the command.
const runMainEnv = "AGENTSMD_TEST_RUN_MAIN"

func TestMain(m *testing.M) {
	if os.Getenv(runMainEnv) == "1" {
		main()
		return
	}
	os.Exit(m.Run())
}

// writeTree lays out files under root; keys are relative paths.
func writeTree(t *testing.T, root string, files map[string]string) {
	t.Helper()
	for rel, content := range files {
		abs := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(abs, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

// sourceLayers is a minimal but representative constitution: a rule in
// CLAUDE.md, a parent-relative ADR link and a shell comment inside a fence in
// .claude/engineering.md, and an H6 in .claude/stack.md (must not become H7).
func sourceLayers() map[string]string {
	return map[string]string{
		"go.mod":    "module example.com/fake\n\ngo 1.25.0\n",
		"CLAUDE.md": "# Constitution\n\n## Rules\n\n1. Halt on violation.\n",
		".claude/engineering.md": "# Engineering\n\n## Go Style\n\nSee [ADR-010](../docs/adr/ADR-010.md).\n\n" +
			"```sh\n# shell comment survives\ntask ci\n```\n",
		".claude/workflow.md": "# Workflow\n\nThree passes.\n",
		".claude/stack.md":    "# Stack\n\n###### Budgets\n",
	}
}

// generatedFromLayers is the exact AGENTS.md that sourceLayers must produce:
// banner, H1, preamble, then each layer behind a rule and a source marker with
// headings demoted one level and ../ links made root-relative.
const generatedFromLayers = "<!-- GENERATED FILE — DO NOT EDIT DIRECTLY. Regenerate with: task agents:build (ADR-022). -->\n" +
	"\n" +
	"# Agent Context — Go Performance Starter\n" +
	"\n" +
	"> Generated from `CLAUDE.md` + `.claude/engineering.md` + `.claude/workflow.md` + `.claude/stack.md`.\n" +
	"> Edit those source layers, then run `task agents:build`. Do not edit this file directly.\n" +
	"\n" +
	"---\n" +
	"\n" +
	"<!-- source: CLAUDE.md -->\n" +
	"\n" +
	"## Constitution\n" +
	"\n" +
	"### Rules\n" +
	"\n" +
	"1. Halt on violation.\n" +
	"\n" +
	"---\n" +
	"\n" +
	"<!-- source: .claude/engineering.md -->\n" +
	"\n" +
	"## Engineering\n" +
	"\n" +
	"### Go Style\n" +
	"\n" +
	"See [ADR-010](docs/adr/ADR-010.md).\n" +
	"\n" +
	"```sh\n" +
	"# shell comment survives\n" +
	"task ci\n" +
	"```\n" +
	"\n" +
	"---\n" +
	"\n" +
	"<!-- source: .claude/workflow.md -->\n" +
	"\n" +
	"## Workflow\n" +
	"\n" +
	"Three passes.\n" +
	"\n" +
	"---\n" +
	"\n" +
	"<!-- source: .claude/stack.md -->\n" +
	"\n" +
	"## Stack\n" +
	"\n" +
	"###### Budgets\n"

func TestGenerate(t *testing.T) {
	tests := []struct {
		name    string
		files   func(files map[string]string)
		want    string // exact output when non-empty
		wantEnd string // required suffix when want is empty
		wantErr string // substring of the error
	}{
		{
			name: "concatenates layers in order with demoted headings and root-relative links",
			want: generatedFromLayers,
		},
		{
			name: "trailing blank lines in the last layer collapse to a single newline",
			files: func(files map[string]string) {
				files[".claude/stack.md"] = "# Stack\n\n###### Budgets\n\n\n\n"
			},
			wantEnd: "## Stack\n\n###### Budgets\n",
		},
		{
			name: "missing source layer errors naming the layer",
			files: func(files map[string]string) {
				delete(files, ".claude/stack.md")
			},
			wantErr: "reading source .claude/stack.md",
		},
		{
			name: "missing CLAUDE.md errors naming the layer",
			files: func(files map[string]string) {
				delete(files, "CLAUDE.md")
			},
			wantErr: "reading source CLAUDE.md",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			root := t.TempDir()
			files := sourceLayers()
			if tt.files != nil {
				tt.files(files)
			}
			writeTree(t, root, files)

			got, err := generate(root)
			if tt.wantErr != "" {
				if err == nil {
					t.Fatalf("expected error containing %q, got output:\n%s", tt.wantErr, got)
				}
				if !strings.Contains(err.Error(), tt.wantErr) {
					t.Fatalf("error %q does not contain %q", err, tt.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if tt.want != "" && string(got) != tt.want {
				t.Errorf("generated output mismatch\n--- got ---\n%s\n--- want ---\n%s", got, tt.want)
			}
			if tt.wantEnd != "" {
				if !strings.HasSuffix(string(got), tt.wantEnd) {
					t.Errorf("output does not end with %q; tail is %q", tt.wantEnd, tail(string(got), len(tt.wantEnd)+8))
				}
				if strings.HasSuffix(string(got), "\n\n") {
					t.Errorf("output ends with more than one newline: %q", tail(string(got), 8))
				}
			}
		})
	}
}

func tail(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[len(s)-n:]
}

func TestDemoteHeadings(t *testing.T) {
	tests := []struct {
		name string
		in   string
		want string
	}{
		{
			name: "H1 becomes H2",
			in:   "# Title",
			want: "## Title",
		},
		{
			name: "H5 becomes H6",
			in:   "##### Deep",
			want: "###### Deep",
		},
		{
			name: "H6 is capped and not demoted to H7",
			in:   "###### Deepest",
			want: "###### Deepest",
		},
		{
			name: "every heading in a document is demoted",
			in:   "# A\n\ntext\n\n## B\n\n### C",
			want: "## A\n\ntext\n\n### B\n\n#### C",
		},
		{
			name: "hash comment inside a backtick fence is untouched",
			in:   "```sh\n# not a heading\necho hi\n```",
			want: "```sh\n# not a heading\necho hi\n```",
		},
		{
			name: "hash comment inside a tilde fence is untouched",
			in:   "~~~\n# not a heading\n~~~",
			want: "~~~\n# not a heading\n~~~",
		},
		{
			name: "heading after a fence closes is demoted again",
			in:   "# A\n```\n# kept\n```\n# B",
			want: "## A\n```\n# kept\n```\n## B",
		},
		{
			name: "indented fence marker still toggles fence state",
			in:   "  ```\n# kept\n  ```\n# B",
			want: "  ```\n# kept\n  ```\n## B",
		},
		{
			name: "unterminated fence protects everything after it",
			in:   "# A\n```\n# kept\n# also kept",
			want: "## A\n```\n# kept\n# also kept",
		},
		{
			name: "hash not at line start is untouched",
			in:   "see issue #1 and C# notes",
			want: "see issue #1 and C# notes",
		},
		{
			name: "indented hash is not treated as a heading",
			in:   "    # code block comment",
			want: "    # code block comment",
		},
		{
			name: "blank lines and plain text pass through",
			in:   "\nplain\n\n",
			want: "\nplain\n\n",
		},
		{
			name: "empty input",
			in:   "",
			want: "",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := demoteHeadings(tt.in); got != tt.want {
				t.Errorf("demoteHeadings(%q)\n got %q\nwant %q", tt.in, got, tt.want)
			}
		})
	}
}

func TestRepoRoot(t *testing.T) {
	tests := []struct {
		name    string
		files   map[string]string
		workdir string // relative to the temp root
		wantErr bool
	}{
		{
			name:    "finds go.mod in the working directory",
			files:   map[string]string{"go.mod": "module x\n"},
			workdir: ".",
		},
		{
			name:    "walks up from a nested directory",
			files:   map[string]string{"go.mod": "module x\n", "a/b/c/.keep": ""},
			workdir: "a/b/c",
		},
		{
			name:    "errors when no ancestor has go.mod",
			files:   map[string]string{"a/.keep": ""},
			workdir: "a",
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			root := t.TempDir()
			if tt.wantErr && ancestorHasGoMod(root) {
				t.Skip("temp dir lives under a Go module; cannot assert the not-found path")
			}
			writeTree(t, root, tt.files)
			t.Chdir(filepath.Join(root, tt.workdir))

			got, err := repoRoot()
			if tt.wantErr {
				if err == nil {
					t.Fatalf("expected error, got root %q", got)
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if !sameDir(t, got, root) {
				t.Errorf("repoRoot() = %q, want %q", got, root)
			}
		})
	}
}

// ancestorHasGoMod reports whether any directory above dir contains a go.mod,
// which would make the not-found case unreachable on this machine.
func ancestorHasGoMod(dir string) bool {
	for parent := filepath.Dir(dir); parent != dir; dir, parent = parent, filepath.Dir(parent) {
		if _, err := os.Stat(filepath.Join(parent, "go.mod")); err == nil {
			return true
		}
	}
	return false
}

// sameDir compares two paths by identity so macOS's /var -> /private/var
// symlink cannot cause a false mismatch.
func sameDir(t *testing.T, a, b string) bool {
	t.Helper()
	ai, err := os.Stat(a)
	if err != nil {
		t.Fatal(err)
	}
	bi, err := os.Stat(b)
	if err != nil {
		t.Fatal(err)
	}
	return os.SameFile(ai, bi)
}

// TestMainVerdict drives main() in a child process (see TestMain) from a
// synthetic repo root and asserts the gate's verdict: exit code, message, and
// the AGENTS.md left on disk. This is the ADR-022 TC-1 drift check.
func TestMainVerdict(t *testing.T) {
	tests := []struct {
		name      string
		args      []string
		files     func(files map[string]string)
		wantExit  int
		wantOut   string // substring of combined stdout+stderr
		wantFile  string // exact AGENTS.md content after the run, when non-empty
		wantNoGen bool   // AGENTS.md must not have been (re)written
	}{
		{
			name:     "build writes AGENTS.md from the source layers",
			args:     []string{"build"},
			wantExit: 0,
			wantOut:  "✅ Wrote AGENTS.md",
			wantFile: generatedFromLayers,
		},
		{
			name:     "no argument defaults to build",
			args:     nil,
			wantExit: 0,
			wantOut:  "✅ Wrote AGENTS.md",
			wantFile: generatedFromLayers,
		},
		{
			name: "build overwrites a stale AGENTS.md",
			args: []string{"build"},
			files: func(files map[string]string) {
				files["AGENTS.md"] = "# hand-edited\n"
			},
			wantExit: 0,
			wantFile: generatedFromLayers,
		},
		{
			name: "check passes when AGENTS.md is in sync",
			args: []string{"check"},
			files: func(files map[string]string) {
				files["AGENTS.md"] = generatedFromLayers
			},
			wantExit: 0,
			wantOut:  "✅ AGENTS.md is in sync",
		},
		{
			name: "check tolerates trailing newline differences",
			args: []string{"check"},
			files: func(files map[string]string) {
				files["AGENTS.md"] = generatedFromLayers + "\n\n"
			},
			wantExit: 0,
			wantOut:  "✅ AGENTS.md is in sync",
		},
		{
			name: "check fails when a source layer changed after generation",
			args: []string{"check"},
			files: func(files map[string]string) {
				files["AGENTS.md"] = generatedFromLayers
				files["CLAUDE.md"] = "# Constitution\n\n## Rules\n\n1. Halt on violation.\n2. New rule.\n"
			},
			wantExit:  1,
			wantOut:   "❌ AGENTS.md is out of sync with its sources",
			wantNoGen: true,
		},
		{
			name: "check fails when AGENTS.md was hand-edited",
			args: []string{"check"},
			files: func(files map[string]string) {
				files["AGENTS.md"] = strings.Replace(generatedFromLayers, "1. Halt on violation.", "1. Carry on.", 1)
			},
			wantExit:  1,
			wantOut:   "❌ AGENTS.md is out of sync with its sources",
			wantNoGen: true,
		},
		{
			name:     "check fails when AGENTS.md is missing",
			args:     []string{"check"},
			wantExit: 1,
			wantOut:  "reading AGENTS.md",
		},
		{
			name:     "unknown mode fails",
			args:     []string{"lint"},
			wantExit: 1,
			wantOut:  `unknown mode "lint"`,
		},
		{
			name: "missing source layer fails before writing",
			args: []string{"build"},
			files: func(files map[string]string) {
				delete(files, ".claude/workflow.md")
			},
			wantExit: 1,
			wantOut:  "reading source .claude/workflow.md",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			root := t.TempDir()
			files := sourceLayers()
			if tt.files != nil {
				tt.files(files)
			}
			writeTree(t, root, files)
			before := files["AGENTS.md"]

			exit, out := runMain(t, root, tt.args...)
			if exit != tt.wantExit {
				t.Fatalf("exit code = %d, want %d; output:\n%s", exit, tt.wantExit, out)
			}
			if !strings.Contains(out, tt.wantOut) {
				t.Errorf("output does not contain %q:\n%s", tt.wantOut, out)
			}

			after, err := os.ReadFile(filepath.Join(root, "AGENTS.md"))
			if tt.wantFile != "" {
				if err != nil {
					t.Fatalf("AGENTS.md not written: %v", err)
				}
				if string(after) != tt.wantFile {
					t.Errorf("AGENTS.md content mismatch\n--- got ---\n%s\n--- want ---\n%s", after, tt.wantFile)
				}
			}
			if tt.wantNoGen && string(after) != before {
				t.Errorf("check must not rewrite AGENTS.md; it changed to:\n%s", after)
			}
		})
	}
}

// runMain re-executes the test binary as the agentsmd command with root as the
// working directory and returns its exit code and combined output.
func runMain(t *testing.T, root string, args ...string) (int, string) {
	t.Helper()
	cmd := exec.Command(os.Args[0], args...)
	cmd.Dir = root
	// Under -race, a clean exit sleeps atexit_sleep_ms (default 1s) to catch
	// at-exit races; the child is single-goroutine, so skip the wait.
	gorace := strings.TrimSpace(os.Getenv("GORACE") + " atexit_sleep_ms=0")
	cmd.Env = append(os.Environ(), runMainEnv+"=1", "GORACE="+gorace)
	out, err := cmd.CombinedOutput()
	if err == nil {
		return 0, string(out)
	}
	var exitErr *exec.ExitError
	if !errors.As(err, &exitErr) {
		t.Fatalf("running %s %v: %v", os.Args[0], args, err)
	}
	return exitErr.ExitCode(), string(out)
}

func TestRewriteParentLinks(t *testing.T) {
	tests := []struct {
		name string
		in   string
		want string
	}{
		{
			name: "adr link from .claude resolves at repo root",
			in:   "Full rationale in [ADR-019](../docs/adr/ADR-019-Template-Scope-Boundary.md).",
			want: "Full rationale in [ADR-019](docs/adr/ADR-019-Template-Scope-Boundary.md).",
		},
		{
			name: "repo root file link",
			in:   "The cross-tool agent context lives in [`AGENTS.md`](../AGENTS.md) at the repo root.",
			want: "The cross-tool agent context lives in [`AGENTS.md`](AGENTS.md) at the repo root.",
		},
		{
			name: "multiple links on one line",
			in:   "[a](../docs/a.md) and [b](../docs/b.md)",
			want: "[a](docs/a.md) and [b](docs/b.md)",
		},
		{
			name: "root-relative link untouched",
			in:   "[ADR-003](docs/adr/ADR-003-Database-Access.md)",
			want: "[ADR-003](docs/adr/ADR-003-Database-Access.md)",
		},
		{
			name: "same-directory link untouched",
			in:   "[architect](roles/architect.md)",
			want: "[architect](roles/architect.md)",
		},
		{
			name: "doubled parent prefix collapses fully",
			in:   "[x](../../docs/x.md)",
			want: "[x](docs/x.md)",
		},
		{
			name: "parent path outside link syntax untouched",
			in:   "run `cd ../elsewhere` first",
			want: "run `cd ../elsewhere` first",
		},
		{
			name: "empty string",
			in:   "",
			want: "",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := rewriteParentLinks(tt.in); got != tt.want {
				t.Errorf("rewriteParentLinks(%q) = %q, want %q", tt.in, got, tt.want)
			}
		})
	}
}
