package main

import (
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func writeTree(t *testing.T, root string, files map[string]string) {
	t.Helper()
	for rel, content := range files {
		abs := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(abs, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

func TestCompare(t *testing.T) {
	tests := []struct {
		name string
		want map[string][]byte // what the generator produced in scratch
		got  map[string][]byte // what is committed under the repo
		out  []string
	}{
		{
			name: "identical output is clean",
			want: map[string][]byte{"a.go": []byte("x")},
			got:  map[string][]byte{"a.go": []byte("x")},
		},
		{
			name: "changed content is drift",
			want: map[string][]byte{"a.go": []byte("new")},
			got:  map[string][]byte{"a.go": []byte("old")},
			out:  []string{"a.go: committed output differs from what the generator produces"},
		},
		{
			name: "generator output missing from the repo",
			want: map[string][]byte{"a.go": []byte("x"), "b.go": []byte("y")},
			got:  map[string][]byte{"a.go": []byte("x")},
			out:  []string{"b.go: generator produces this file but it is not committed"},
		},
		{
			name: "committed generated file no source produces is stale",
			want: map[string][]byte{"a.go": []byte("x")},
			got:  map[string][]byte{"a.go": []byte("x"), "zombie.go": []byte("z")},
			out:  []string{"zombie.go: committed generated file that no source produces (stale)"},
		},
		{
			name: "findings are sorted by path for stable output",
			want: map[string][]byte{"b.go": []byte("1"), "a.go": []byte("1")},
			got:  map[string][]byte{"b.go": []byte("2"), "a.go": []byte("2")},
			out: []string{
				"a.go: committed output differs from what the generator produces",
				"b.go: committed output differs from what the generator produces",
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := compare(tt.want, tt.got)
			if !reflect.DeepEqual(got, tt.out) {
				t.Errorf("compare() = %q, want %q", got, tt.out)
			}
		})
	}
}

func TestCollectOutputs(t *testing.T) {
	root := t.TempDir()
	writeTree(t, root, map[string]string{
		"internal/database/db.go":                "// Code generated by sqlc. DO NOT EDIT.\npackage database\n",
		"internal/database/users.sql.go":         "// Code generated by sqlc. DO NOT EDIT.\npackage database\n",
		"internal/database/fixtures/fixtures.go": "package fixtures\n",
		"internal/database/notes.sql":            "-- not go\n",
		"internal/view/pages/home_templ.go":      "// Code generated by templ - DO NOT EDIT.\n",
		"internal/view/pages/home.templ":         "package pages\n",
		"internal/view/props.go":                 "package view\n",
		"internal/view/tokens_test.go":           "package view\n",
	})

	tests := []struct {
		name string
		gen  generator
		want []string
	}{
		{
			name: "sqlc collects only header-marked .go files directly in the out dir",
			gen:  sqlcGenerator,
			want: []string{"internal/database/db.go", "internal/database/users.sql.go"},
		},
		{
			name: "templ collects _templ.go files recursively under internal/view",
			gen:  templGenerator,
			want: []string{"internal/view/pages/home_templ.go"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := collectOutputs(root, tt.gen)
			if err != nil {
				t.Fatal(err)
			}
			var keys []string
			for k := range got {
				keys = append(keys, k)
			}
			sortStrings(keys)
			if !reflect.DeepEqual(keys, tt.want) {
				t.Errorf("collected %q, want %q", keys, tt.want)
			}
		})
	}
}

func TestCopySources(t *testing.T) {
	root := t.TempDir()
	writeTree(t, root, map[string]string{
		"sqlc.yaml":                         "version: \"2\"\n",
		"sql/queries/users.sql":             "-- name: GetUser :one\n",
		"sql/schema/001.sql":                "create table users();\n",
		"internal/view/pages/home.templ":    "package pages\n",
		"internal/view/pages/home_templ.go": "generated\n",
		"internal/view/props.go":            "package view\n",
		"internal/database/db.go":           "// Code generated by sqlc. DO NOT EDIT.\n",
	})

	tests := []struct {
		name        string
		gen         generator
		wantPresent []string
		wantAbsent  []string
	}{
		{
			name:        "sqlc copies config and sql tree, not the committed output",
			gen:         sqlcGenerator,
			wantPresent: []string{"sqlc.yaml", "sql/queries/users.sql", "sql/schema/001.sql"},
			wantAbsent:  []string{"internal/database/db.go"},
		},
		{
			name:        "templ copies only .templ sources, not generated or hand-written go",
			gen:         templGenerator,
			wantPresent: []string{"internal/view/pages/home.templ"},
			wantAbsent:  []string{"internal/view/pages/home_templ.go", "internal/view/props.go"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			scratch := t.TempDir()
			if err := copySources(root, scratch, tt.gen); err != nil {
				t.Fatal(err)
			}
			for _, rel := range tt.wantPresent {
				if _, err := os.Stat(filepath.Join(scratch, rel)); err != nil {
					t.Errorf("%s should have been copied: %v", rel, err)
				}
			}
			for _, rel := range tt.wantAbsent {
				if _, err := os.Stat(filepath.Join(scratch, rel)); err == nil {
					t.Errorf("%s should not have been copied", rel)
				}
			}
		})
	}
}

// fakeRunner stands in for the generator binaries: it writes the given files
// into the scratch root (relative paths) as if the tool had produced them.
func fakeRunner(outputs map[string]string, err error) runFn {
	return func(scratch string, _ generator) error {
		if err != nil {
			return err
		}
		for rel, content := range outputs {
			abs := filepath.Join(scratch, rel)
			if mkErr := os.MkdirAll(filepath.Dir(abs), 0o755); mkErr != nil {
				return mkErr
			}
			if wErr := os.WriteFile(abs, []byte(content), 0o644); wErr != nil {
				return wErr
			}
		}
		return nil
	}
}

func TestCheckGenerator(t *testing.T) {
	const header = "// Code generated by sqlc. DO NOT EDIT.\n"
	repoFiles := map[string]string{
		"sqlc.yaml":               "version: \"2\"\n",
		"sql/queries/users.sql":   "-- name: GetUser :one\n",
		"internal/database/db.go": header + "package database // v1\n",
	}

	tests := []struct {
		name      string
		lookPath  func(string) (string, error)
		run       runFn
		wantState string
		wantMsgs  []string
	}{
		{
			name:      "in sync passes",
			lookPath:  func(string) (string, error) { return "/bin/sqlc", nil },
			run:       fakeRunner(map[string]string{"internal/database/db.go": header + "package database // v1\n"}, nil),
			wantState: statePass,
		},
		{
			name:      "regenerated output differs — drift",
			lookPath:  func(string) (string, error) { return "/bin/sqlc", nil },
			run:       fakeRunner(map[string]string{"internal/database/db.go": header + "package database // v2\n"}, nil),
			wantState: stateDrift,
			wantMsgs:  []string{"internal/database/db.go: committed output differs from what the generator produces"},
		},
		{
			name:      "generator not installed is reported, not silently passed",
			lookPath:  func(string) (string, error) { return "", errors.New("not found") },
			run:       fakeRunner(nil, nil),
			wantState: stateSkipped,
			wantMsgs:  []string{"sqlc not found on PATH — install it (see Taskfile db:generate) to run this check"},
		},
		{
			name:      "generator failure is an error state",
			lookPath:  func(string) (string, error) { return "/bin/sqlc", nil },
			run:       fakeRunner(nil, errors.New("boom")),
			wantState: stateError,
			wantMsgs:  []string{"sqlc generate failed: boom"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			root := t.TempDir()
			writeTree(t, root, repoFiles)
			res := checkGenerator(root, sqlcGenerator, tt.lookPath, tt.run)
			if res.State != tt.wantState {
				t.Errorf("state = %q, want %q (msgs %q)", res.State, tt.wantState, res.Messages)
			}
			if !reflect.DeepEqual(res.Messages, tt.wantMsgs) {
				t.Errorf("messages = %q, want %q", res.Messages, tt.wantMsgs)
			}
			// A check must never touch the working tree: the committed file
			// is byte-identical afterwards even when drift was found.
			got, _ := os.ReadFile(filepath.Join(root, "internal/database/db.go"))
			if string(got) != repoFiles["internal/database/db.go"] {
				t.Errorf("check mutated the working tree: %q", got)
			}
		})
	}
}

func TestExitCode(t *testing.T) {
	tests := []struct {
		name   string
		mode   string
		states []string
		want   int
	}{
		{"all pass in block mode", "block", []string{statePass, statePass}, 0},
		{"drift in warn mode reports but exits 0", "warn", []string{stateDrift, statePass}, 0},
		{"drift in block mode fails", "block", []string{statePass, stateDrift}, 1},
		{"missing tool in warn mode exits 0", "warn", []string{stateSkipped}, 0},
		{"missing tool in block mode fails — a silent skip would be a hole in the gate", "block", []string{stateSkipped}, 1},
		{"generator error fails in either mode", "warn", []string{stateError}, 1},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := exitCode(tt.mode, tt.states); got != tt.want {
				t.Errorf("exitCode(%q, %v) = %d, want %d", tt.mode, tt.states, got, tt.want)
			}
		})
	}
}

func TestLabelForState(t *testing.T) {
	for state, want := range map[string]string{
		statePass:    "PASS",
		stateDrift:   "WARNING",
		stateSkipped: "WARNING",
		stateError:   "ERROR",
	} {
		if got := label("warn", state); got != want {
			t.Errorf("label(warn, %s) = %q, want %q", state, got, want)
		}
	}
	if got := label("block", stateDrift); got != "BLOCKER" {
		t.Errorf("label(block, drift) = %q, want BLOCKER", got)
	}
	if !strings.Contains(label("block", stateSkipped), "BLOCKER") {
		t.Errorf("a skipped generator in block mode must read as a BLOCKER")
	}
}
