// Command checkgenerated verifies that the committed generator output is what
// the generators produce from their sources: sqlc (`internal/database/`,
// ADR-003) and templ (`internal/view/**/*_templ.go`, ADR-017). The
// PreToolUse guard blocks agent hand-edits at write time, but nothing caught
// drift arriving another way — a manual edit, a generator version bump, a
// forgotten `task db:generate` — until this check (the first deferred TODO
// in ADR-033).
//
// It never touches the working tree: each generator's sources are copied
// into a scratch directory, the generator runs there, and its output is
// diffed against the committed files. The remedy for drift is the normal
// regeneration task (`task db:generate` / `task templ:generate`) plus a
// commit.
//
// Usage (from the repo root):
//
//	go run ./scripts/checkgenerated [-mode=warn|block]
//
// -mode=warn (the default, and what task ci runs today) reports drift and
// exits 0 — the ADR-033 graduation rule: a new check earns block status
// after seven clean days or one real catch. -mode=block exits non-zero on
// drift and on a missing generator (a silent skip would be a hole in the
// gate). A generator that is installed but fails is an error in either mode.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// generator describes one codegen tool: which sources it reads (copied into
// scratch), how to invoke it there, and how to recognise its output files in
// the repo so hand-written neighbours (sqlc's fixtures/, templ's .go props
// files) are left out of the comparison.
type generator struct {
	name     string   // tool name, also the binary looked up on PATH
	adr      string   // governing ADR, for the report line
	sources  []string // files/dirs relative to root to copy into scratch
	args     []string // arguments to the tool, run with cwd = scratch
	isSource func(rel string) bool
	// outDir is where output lives (relative to root); isOutput decides
	// whether a file under it is this generator's.
	outDir    string
	recursive bool
	isOutput  func(rel string, content []byte) bool
}

var sqlcGenerator = generator{
	name:      "sqlc",
	adr:       "ADR-003",
	sources:   []string{"sqlc.yaml", "sql"},
	args:      []string{"generate"},
	isSource:  func(string) bool { return true },
	outDir:    "internal/database",
	recursive: false, // fixtures/ is hand-written; sqlc writes flat into outDir
	isOutput: func(rel string, content []byte) bool {
		return strings.HasSuffix(rel, ".go") && bytes.HasPrefix(content, []byte("// Code generated by sqlc."))
	},
}

var templGenerator = generator{
	name:    "templ",
	adr:     "ADR-017",
	sources: []string{"internal/view"},
	// No -path: templ embeds each source's path relative to its working
	// directory in the generated templ.Error calls, so the scratch run must
	// start from the scratch root exactly like `task templ:generate` starts
	// from the repo root — otherwise every file "drifts" by that prefix.
	args:      []string{"generate"},
	isSource:  func(rel string) bool { return strings.HasSuffix(rel, ".templ") },
	outDir:    "internal/view",
	recursive: true,
	isOutput:  func(rel string, _ []byte) bool { return strings.HasSuffix(rel, "_templ.go") },
}

var generators = []generator{sqlcGenerator, templGenerator}

const (
	statePass    = "pass"
	stateDrift   = "drift"
	stateSkipped = "skipped" // tool not installed
	stateError   = "error"   // tool installed but failed
)

type result struct {
	Generator generator
	State     string
	Messages  []string
}

// runFn executes a generator with cwd = scratch. Injected so the
// orchestration is testable without the binaries.
type runFn func(scratch string, g generator) error

func execGenerator(scratch string, g generator) error {
	cmd := exec.Command(g.name, g.args...)
	cmd.Dir = scratch
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%w: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// copySources copies the generator's inputs from root into scratch,
// preserving relative paths and applying g.isSource per file.
func copySources(root, scratch string, g generator) error {
	for _, src := range g.sources {
		abs := filepath.Join(root, src)
		err := filepath.WalkDir(abs, func(path string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() {
				return nil
			}
			rel, _ := filepath.Rel(root, path)
			if !g.isSource(filepath.ToSlash(rel)) {
				return nil
			}
			content, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			dst := filepath.Join(scratch, rel)
			if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
				return err
			}
			return os.WriteFile(dst, content, 0o644)
		})
		if err != nil {
			return fmt.Errorf("copy %s: %w", src, err)
		}
	}
	return nil
}

// collectOutputs returns the generator's output files under base (repo root
// or scratch root) keyed by slash-separated path relative to base.
func collectOutputs(base string, g generator) (map[string][]byte, error) {
	out := map[string][]byte{}
	dir := filepath.Join(base, g.outDir)
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			if os.IsNotExist(err) && path == dir {
				return nil // generator produced nothing (or nothing committed)
			}
			return err
		}
		if d.IsDir() {
			if path != dir && !g.recursive {
				return filepath.SkipDir
			}
			return nil
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(base, path)
		rel = filepath.ToSlash(rel)
		if g.isOutput(rel, content) {
			out[rel] = content
		}
		return nil
	})
	return out, err
}

// compare diffs generator output (want) against committed files (got).
func compare(want, got map[string][]byte) []string {
	var findings []string
	for rel, fresh := range want {
		committed, ok := got[rel]
		switch {
		case !ok:
			findings = append(findings, rel+": generator produces this file but it is not committed")
		case !bytes.Equal(fresh, committed):
			findings = append(findings, rel+": committed output differs from what the generator produces")
		}
	}
	for rel := range got {
		if _, ok := want[rel]; !ok {
			findings = append(findings, rel+": committed generated file that no source produces (stale)")
		}
	}
	sortStrings(findings)
	return findings
}

func checkGenerator(root string, g generator, lookPath func(string) (string, error), run runFn) result {
	res := result{Generator: g}
	if _, err := lookPath(g.name); err != nil {
		res.State = stateSkipped
		res.Messages = []string{fmt.Sprintf("%s not found on PATH — install it (see Taskfile db:generate) to run this check", g.name)}
		return res
	}
	scratch, err := os.MkdirTemp("", "checkgenerated-"+g.name+"-")
	if err != nil {
		res.State = stateError
		res.Messages = []string{fmt.Sprintf("scratch dir: %v", err)}
		return res
	}
	defer func() { _ = os.RemoveAll(scratch) }() // best-effort scratch cleanup

	if err := copySources(root, scratch, g); err != nil {
		res.State = stateError
		res.Messages = []string{err.Error()}
		return res
	}
	if err := run(scratch, g); err != nil {
		res.State = stateError
		res.Messages = []string{fmt.Sprintf("%s generate failed: %v", g.name, err)}
		return res
	}
	fresh, err := collectOutputs(scratch, g)
	if err != nil {
		res.State = stateError
		res.Messages = []string{fmt.Sprintf("read %s output: %v", g.name, err)}
		return res
	}
	committed, err := collectOutputs(root, g)
	if err != nil {
		res.State = stateError
		res.Messages = []string{fmt.Sprintf("read committed %s output: %v", g.name, err)}
		return res
	}
	if findings := compare(fresh, committed); len(findings) > 0 {
		res.State = stateDrift
		res.Messages = findings
		return res
	}
	res.State = statePass
	return res
}

// exitCode applies the mode to the per-generator states. Errors always fail;
// drift and a missing tool fail only in block mode.
func exitCode(mode string, states []string) int {
	for _, s := range states {
		switch s {
		case stateError:
			return 1
		case stateDrift, stateSkipped:
			if mode == "block" {
				return 1
			}
		}
	}
	return 0
}

func label(mode, state string) string {
	switch state {
	case statePass:
		return "PASS"
	case stateError:
		return "ERROR"
	default: // drift, skipped
		if mode == "block" {
			return "BLOCKER"
		}
		return "WARNING"
	}
}

func remedy(g generator) string {
	if g.name == "sqlc" {
		return "run `task db:generate` and commit internal/database/ (ADR-003); if a file is stale, delete it"
	}
	return "run `task templ:generate` and commit the *_templ.go files (ADR-017); if a file is stale, delete it"
}

// sortStrings is an insertion sort — the slices here are a handful of paths.
func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j] < s[j-1]; j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}

func main() {
	mode := flag.String("mode", "warn", "warn: report drift, exit 0; block: fail on drift or a missing generator")
	flag.Parse()
	if *mode != "warn" && *mode != "block" {
		fmt.Fprintf(os.Stderr, "checkgenerated: -mode must be warn or block, got %q\n", *mode)
		os.Exit(2)
	}

	root, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "checkgenerated: %v\n", err)
		os.Exit(1)
	}

	var states []string
	for _, g := range generators {
		res := checkGenerator(root, g, exec.LookPath, execGenerator)
		states = append(states, res.State)
		fmt.Printf("%-8s check:generated/%-6s (%s, regeneration drift)\n", label(*mode, res.State), g.name, g.adr)
		for _, m := range res.Messages {
			fmt.Printf("         %s\n", m)
		}
		if res.State == stateDrift {
			fmt.Printf("         remedy: %s\n", remedy(g))
		}
	}
	os.Exit(exitCode(*mode, states))
}
